# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8 Plus",
  "iPhone XS Max",
  "iPad Pro (12.9-inch)",
])

languages([
  "en-US",
  ["pt", "pt_PT"] # Portuguese with Portugal locale
])

# The name of the scheme which contains the UI Tests
scheme("BuildTrackerUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["TESTING_UI"])

# Choose which project/workspace to use
project "./BuildTracker.xcodeproj"

# Custom
number_of_retries 0
stop_after_first_error true
erase_simulator false
